# Generated by Django 4.2.6 on 2023-10-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('peso', models.FloatField()),
                ('descricao', models.TextField()),
                ('valor', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
                ('categoria', models.CharField(choices=[('brigadeiro', 'Brigadeiro'), ('bolacha', 'Bolacha'), ('brownie', 'Brownie'), ('torta', 'Torta')], default='brigadeiro', max_length=255)),
            ],
        ),
    ]
