# Generated by Django 4.2.6 on 2023-10-24 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quitutes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doces',
            new_name='Doce',
        ),
    ]
