# Generated by Django 4.2.6 on 2023-10-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quitutes', '0002_rename_doces_doce'),
    ]

    operations = [
        migrations.AddField(
            model_name='doce',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
